# Generated by Django 3.2.16 on 2023-01-18 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_devtool'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Devtool',
            new_name='DevtoolList',
        ),
    ]
